version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - br0
  app:
    build: .
    restart: always
    expose:
      - "3000"
    env_file:
      - ".env.development.local"

volumes:
  postgres-data:
networks:
  br0:
    driver: bridge